# Generated by Django 3.2 on 2021-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksDB', '0002_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(),
        ),
    ]
