# Generated by Django 3.2 on 2021-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksDB', '0003_auto_20210412_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(max_length=64),
        ),
    ]
