# Generated by Django 3.2 on 2021-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksDB', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_src',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
