# Generated by Django 3.2 on 2021-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksDB', '0006_auto_20210413_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_src',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
